name: Convert IP List to RouterOS Commands

on:
  push:
    branches: [ main ]

  schedule:
  - cron: "0 15 * * *"

  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requests
      run: pip install requests

    - name: Run conversion script
      run: python ipsum-Level3-convert_to_routeros.py

    - name: Commit and push changes
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add ipsum-Level3.rsc
        git commit -m "Update RouterOS commands"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
