name: Convert stamparm/ipsum list of bad IPs(level3) to RouterOS addressList

on:
  schedule:
  - cron: "0 15 * * *"

  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requests
      run: pip install requests

    - name: Run conversion script
      run: python ipsum-Level3-convert_to_routeros.py
      
    - name: Generate tag name
      run: echo "TAG_NAME=$(date +%F-%H-%M)" >> $GITHUB_ENV

    - name: Commit and push changes
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add rsc/ipsum-Level3.rsc
        git commit -m "Update RouterOS commands"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: rsc/ipsum-Level3.rsc
        name: Automatic list generation
        tag_name: ${{ env.TAG_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@v0.3.3
      with:
        keep_latest: 2
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload log files
      uses: actions/upload-artifact@v4
      with:
        name: Logs
        path: logs/*.log
      if: ${{ always() }}
